### ISSUE TITLE
Add support for mac and linux

### ISSUE THREAD

**Issue by kaiyan-sheng** [dmwhite22/CopyFileAndFolderStructure#1]
It would be nice to add support for mac and linux.

Note:
Running on macbook seems to work, but I got an warning/error/info in the log:
```
objc[80670]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fffb27f8cd0) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x107429cd8). One of the two will be used. Which one is undefined.
```

**Comment by dmwhite22** [comment]
I looked around and many people are blaming Apple. However, from some of the other reports, this looks like this warning occurs when the program flips through the directories programmatically. 

When did you get this error? After which step and before which step? I would like to see if I can narrow this down to see where the error is occurring.

**Comment by kaiyan-sheng** [comment]
It's right after the first selection for file directory:
```
*******************************************
**********       Welcome     **************
*******************************************
This program searches subdirectories for   
.csv files from the source path specified  
by the user then copies the folder         
structure with the .csv files to the destin-
ation folder.  This program will only copy 
files where the creation time for the file 
is within the date range specified by the  
user.
Press and key to continue...
objc[83288]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fffb27f8cd0) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x10f98dcd8). One of the two will be used. Which one is undefined.
```

**Comment by dmwhite22** [comment]
I made a couple of changes in branch "mac_warning_fix" by not using the messagebox module and using mac's system events. Lets see if that fixes it.

Can you run with the code in the "mac_warning_fix" branch to see if that fixes your issue?

**Comment by kaiyan-sheng** [comment]
Now it's failing 😬in `mac_warning_fix` branch:
```
********************************************************************
*************************     Welcome     **************************
********************************************************************
This program searches subdirectories for files of a certain type    
specified by the user from the source path specified by the user    
then copies the folder structure with the files to the destination  
folder.  This program will only copy files where the creation time  
for the file is within the date range specified by the user.

Press and key to continue...
Traceback (most recent call last):
  File "CopyFileAndFolderStructure.py", line 228, in <module>
    select_folder_response = display_start_message()
  File "CopyFileAndFolderStructure.py", line 203, in display_start_message
    selected_response = subprocess.run("osascript -e 'Tell application \"System Events\" to display dialog \""
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'osascript -e \'Tell application "System Events" to display dialog "Select the directory from where to pull files?" with title "Continue?"': 'osascript -e \'Tell application "System Events" to display dialog "Select the directory from where to pull files?" with title "Continue?"'
```
